# Generated by Django 4.2.6 on 2023-10-30 13:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_joinedcohort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=50)),
                ('exam_duration', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cohort')),
            ],
        ),
    ]
