# Generated by Django 4.2.6 on 2023-11-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_answermcq_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_availabilty',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
