# Generated by Django 4.2.6 on 2023-11-16 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_exam_exam_availabilty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='exam_duration',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_availabilty',
        ),
    ]
